#!/usr/bin/env bash
# =============================================================================
# deploy.sh — Blue/Green deployment for Prism CRM
# Usage: ./deploy.sh [--rollback]
#
# How it works:
#   1. Detect which slot is currently LIVE (blue or green)
#   2. Build & start the IDLE slot with new code
#   3. Run a health check against the idle slot
#   4. If healthy → update Nginx upstream → reload Nginx
#   5. Stop the OLD slot
#   6. Update the LIVE slot tracker file
#
# Requirements:
#   - Docker + docker compose v2
#   - Nginx on host (not in Docker)
#   - /etc/prism/live_slot file (created on first run)
#   - Nginx config at /etc/nginx/sites-enabled/prismpm.cloud
#     must use an include for the upstream file (see nginx/ dir)
# =============================================================================

set -euo pipefail

# ── Config ────────────────────────────────────────────────────────────────────
PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SLOT_FILE="/etc/prism/live_slot"
NGINX_UPSTREAM_FILE="/etc/nginx/conf.d/prism_upstream.conf"
NGINX_SITE_CONF="/etc/nginx/sites-enabled/prismpm.cloud"
HEALTH_TIMEOUT=60      # seconds to wait for new slot to become healthy
HEALTH_INTERVAL=3      # seconds between health checks
LOG_FILE="/var/log/prism/deploy.log"

# Port assignments per slot
BLUE_BACKEND_PORT=8001
BLUE_FRONTEND_PORT=5174
GREEN_BACKEND_PORT=8002
GREEN_FRONTEND_PORT=5175

# ── Helpers ───────────────────────────────────────────────────────────────────
log() {
  local ts
  ts="$(date '+%Y-%m-%d %H:%M:%S')"
  echo "[${ts}] $*" | tee -a "$LOG_FILE"
}

die() {
  log "ERROR: $*"
  exit 1
}

ensure_dirs() {
  mkdir -p /etc/prism
  mkdir -p "$(dirname "$LOG_FILE")"
}

# ── Slot detection ─────────────────────────────────────────────────────────────
get_live_slot() {
  if [[ -f "$SLOT_FILE" ]]; then
    cat "$SLOT_FILE"
  else
    # First ever deploy — treat blue as default live (may not be running yet)
    echo "blue"
  fi
}

get_idle_slot() {
  local live="$1"
  if [[ "$live" == "blue" ]]; then echo "green"; else echo "blue"; fi
}

slot_backend_port() {
  local slot="$1"
  if [[ "$slot" == "blue" ]]; then echo "$BLUE_BACKEND_PORT"; else echo "$GREEN_BACKEND_PORT"; fi
}

slot_frontend_port() {
  local slot="$1"
  if [[ "$slot" == "blue" ]]; then echo "$BLUE_FRONTEND_PORT"; else echo "$GREEN_FRONTEND_PORT"; fi
}

# ── Docker Compose helpers ─────────────────────────────────────────────────────
compose_file() {
  local slot="$1"
  echo "${PROJECT_DIR}/docker-compose.${slot}.yml"
}

start_slot() {
  local slot="$1"
  local file
  file="$(compose_file "$slot")"
  log "Building and starting slot: $slot (compose file: $file)"
  docker compose -f "$file" --project-name "prism_${slot}" pull --quiet 2>/dev/null || true
  docker compose -f "$file" --project-name "prism_${slot}" up -d --build --remove-orphans
}

stop_slot() {
  local slot="$1"
  local file
  file="$(compose_file "$slot")"
  log "Stopping slot: $slot"
  docker compose -f "$file" --project-name "prism_${slot}" down --remove-orphans || true
}

# ── Health check ───────────────────────────────────────────────────────────────
health_check() {
  local slot="$1"
  local backend_port
  backend_port="$(slot_backend_port "$slot")"
  local elapsed=0

  log "Health check: waiting for backend on port ${backend_port} ..."
  while true; do
    if curl -sf --max-time 5 "http://127.0.0.1:${backend_port}/health" > /dev/null 2>&1; then
      log "Health check passed for slot: $slot (${elapsed}s)"
      return 0
    fi
    if (( elapsed >= HEALTH_TIMEOUT )); then
      log "Health check FAILED for slot: $slot after ${elapsed}s"
      return 1
    fi
    sleep "$HEALTH_INTERVAL"
    (( elapsed += HEALTH_INTERVAL ))
    log "  ... still waiting (${elapsed}s / ${HEALTH_TIMEOUT}s)"
  done
}

# ── Nginx switch ───────────────────────────────────────────────────────────────
switch_nginx() {
  local new_slot="$1"
  local backend_port frontend_port
  backend_port="$(slot_backend_port "$new_slot")"
  frontend_port="$(slot_frontend_port "$new_slot")"

  log "Switching Nginx upstream to slot: $new_slot (backend :${backend_port}, frontend :${frontend_port})"

  # Write new upstream file (included by main nginx site conf)
  cat > "$NGINX_UPSTREAM_FILE" <<EOF
# Auto-generated by deploy.sh — do not edit manually
# Active slot: ${new_slot}
upstream prism_backend {
    server 127.0.0.1:${backend_port};
}
upstream prism_frontend {
    server 127.0.0.1:${frontend_port};
}
EOF

  sudo nginx -t || die "Nginx config test failed — aborting switch"
  sudo nginx -s reload
  log "Nginx reloaded successfully."
}

# ── Rollback ───────────────────────────────────────────────────────────────────
rollback() {
  local live idle
  live="$(get_live_slot)"
  idle="$(get_idle_slot "$live")"

  log "====== ROLLBACK: switching back to slot: $idle ======"

  # Check the old slot is still running
  if ! docker compose -f "$(compose_file "$idle")" --project-name "prism_${idle}" ps --quiet 2>/dev/null | grep -q .; then
    die "Cannot rollback — idle slot '$idle' containers are not running."
  fi

  switch_nginx "$idle"
  echo "$idle" > "$SLOT_FILE"
  log "Rollback complete. Live slot is now: $idle"
  log "The broken slot '$live' is still running — inspect and stop manually when ready:"
  log "  docker compose -f $(compose_file "$live") --project-name prism_${live} down"
}

# ── Main deploy ────────────────────────────────────────────────────────────────
deploy() {
  local live idle
  live="$(get_live_slot)"
  idle="$(get_idle_slot "$live")"

  log "====== DEPLOY START ======"
  log "Live slot  : $live  (backend :$(slot_backend_port "$live"), frontend :$(slot_frontend_port "$live"))"
  log "Target slot: $idle (backend :$(slot_backend_port "$idle"), frontend :$(slot_frontend_port "$idle"))"

  # 1. Start the idle slot with new code
  start_slot "$idle"

  # 2. Health check the new slot
  if ! health_check "$idle"; then
    log "New slot failed health check — stopping it and aborting."
    stop_slot "$idle"
    die "Deploy aborted. Live slot '$live' is still serving traffic."
  fi

  # 3. Switch Nginx to the new slot
  switch_nginx "$idle"

  # 4. Record new live slot
  echo "$idle" > "$SLOT_FILE"
  log "Live slot updated to: $idle"

  # 5. Stop the old slot
  log "Stopping old slot: $live"
  stop_slot "$live"

  log "====== DEPLOY COMPLETE — live slot: $idle ======"
}

# ── Entry point ────────────────────────────────────────────────────────────────
ensure_dirs

case "${1:-}" in
  --rollback)
    rollback
    ;;
  ""|--deploy)
    deploy
    ;;
  *)
    echo "Usage: $0 [--deploy | --rollback]"
    exit 1
    ;;
esac
