"""
form_410.py
Generates a filled Form 410 (Ontario Rental Application) PDF using ReportLab.
Also defines the signature coordinate map for stamping.

The generated PDF matches the layout of the official OREA Form 410.
Signature coordinates are defined per-page, per-signer position.
"""

import io
import logging
from typing import Dict, Any, List, Optional
from reportlab.lib.pagesizes import letter
from reportlab.lib.units import inch
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
from reportlab.pdfgen import canvas as rl_canvas

logger = logging.getLogger("pdf.generators.form_410")

# =============================================================================
# SIGNATURE COORDINATE MAP
# Defines where signatures go on the generated PDF.
# Coordinates are in points (1 inch = 72 points) from top-left.
# These match the layout generated by build_form_410() below.
# =============================================================================

# For a standard letter page (612 x 792 points)
SIGNATURE_COORDS = {
    "applicant_1": {
        "page": 2,
        "x": 72,
        "y": 650,
        "width": 200,
        "height": 50,
        "label": "Signature of Applicant #1"
    },
    "applicant_2": {
        "page": 2,
        "x": 340,
        "y": 650,
        "width": 200,
        "height": 50,
        "label": "Signature of Applicant #2"
    }
}


def get_signature_coords(signer_index: int) -> Dict[str, Any]:
    """
    Returns signature coordinates for a given signer.
    signer_index: 0 = applicant 1, 1 = applicant 2, 2+ = co-applicants (same position as #2)
    """
    if signer_index == 0:
        return SIGNATURE_COORDS["applicant_1"]
    else:
        return SIGNATURE_COORDS["applicant_2"]


# =============================================================================
# PDF GENERATOR
# =============================================================================

def build_form_410(data: Dict[str, Any]) -> bytes:
    """
    Generate a filled Form 410 PDF from application data.

    Args:
        data: dict with application fields:
            - prospect_name       str
            - email               str
            - phone               str
            - building            str
            - unit_number         str
            - lease_start         str  (e.g. '2026-04-01')
            - monthly_rent        str
            - employer_name       str
            - employment_type     str
            - monthly_income      str
            - position_held       str
            - length_of_employment str
            - prior_employer_name  str
            - prior_position_held  str
            - prior_length_of_employment str
            - co_applicants       list of dicts
            - other_occupants     list of dicts
            - has_pet             bool
            - pet_details         str
            - parking_requested   bool
            - reference_1_name    str
            - reference_1_phone   str
            - reference_2_name    str
            - reference_2_phone   str
            - previous_addresses  list of dicts
            - vacating_reason     str

    Returns:
        PDF as bytes
    """
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        rightMargin=0.75 * inch,
        leftMargin=0.75 * inch,
        topMargin=0.75 * inch,
        bottomMargin=0.75 * inch,
    )

    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        "Title", parent=styles["Heading1"],
        fontSize=14, spaceAfter=4, textColor=colors.HexColor("#1e3a5f")
    )
    heading_style = ParagraphStyle(
        "Heading", parent=styles["Heading2"],
        fontSize=11, spaceAfter=4, spaceBefore=10,
        textColor=colors.HexColor("#1e3a5f"),
        borderPad=4,
    )
    label_style = ParagraphStyle(
        "Label", parent=styles["Normal"],
        fontSize=8, textColor=colors.gray, spaceAfter=1
    )
    value_style = ParagraphStyle(
        "Value", parent=styles["Normal"],
        fontSize=10, spaceAfter=6
    )
    small_style = ParagraphStyle(
        "Small", parent=styles["Normal"],
        fontSize=8, textColor=colors.gray
    )

    def field(label: str, value: Any) -> List:
        """Helper to render a label + value pair."""
        return [
            Paragraph(label, label_style),
            Paragraph(str(value) if value else "—", value_style),
        ]

    def section(title: str) -> List:
        return [
            Spacer(1, 8),
            HRFlowable(width="100%", thickness=1, color=colors.HexColor("#1e3a5f")),
            Paragraph(title, heading_style),
        ]

    story = []

    # --- Header ---
    story.append(Paragraph("RENTAL APPLICATION", title_style))
    story.append(Paragraph("Residential — Form 410 | Province of Ontario", small_style))
    story.append(Paragraph("© OREA — For use by members and licensees only", small_style))
    story.append(Spacer(1, 12))

    # --- Property Info ---
    story += section("APPLICATION DETAILS")
    story += [
        Table([
            [
                [Paragraph("Property / Building", label_style), Paragraph(data.get("building") or "—", value_style)],
                [Paragraph("Unit Number", label_style), Paragraph(data.get("unit_number") or "—", value_style)],
            ],
            [
                [Paragraph("Lease Start Date", label_style), Paragraph(data.get("lease_start") or "—", value_style)],
                [Paragraph("Monthly Rent", label_style), Paragraph(f"${data.get('monthly_rent') or '—'}", value_style)],
            ],
        ], colWidths=["50%", "50%"], style=TableStyle([
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ("LEFTPADDING", (0, 0), (-1, -1), 0),
            ("RIGHTPADDING", (0, 0), (-1, -1), 8),
        ]))
    ]

    # --- Applicant #1 ---
    story += section("APPLICANT #1")
    story += [
        Table([
            [
                [Paragraph("Full Name", label_style), Paragraph(data.get("prospect_name") or "—", value_style)],
                [Paragraph("Email", label_style), Paragraph(data.get("email") or "—", value_style)],
                [Paragraph("Phone", label_style), Paragraph(data.get("phone") or "—", value_style)],
            ],
        ], colWidths=["40%", "35%", "25%"], style=TableStyle([
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ("LEFTPADDING", (0, 0), (-1, -1), 0),
            ("RIGHTPADDING", (0, 0), (-1, -1), 8),
        ]))
    ]

    # --- Applicant #1 Employment ---
    story += section("APPLICANT #1 — PRESENT EMPLOYMENT")
    story += [
        Table([
            [
                [Paragraph("Employer", label_style), Paragraph(data.get("employer_name") or "—", value_style)],
                [Paragraph("Employment Type", label_style), Paragraph(data.get("employment_type") or "—", value_style)],
            ],
            [
                [Paragraph("Position Held", label_style), Paragraph(data.get("position_held") or "—", value_style)],
                [Paragraph("Length of Employment", label_style), Paragraph(data.get("length_of_employment") or "—", value_style)],
            ],
            [
                [Paragraph("Monthly Income", label_style), Paragraph(f"${data.get('monthly_income') or '—'}", value_style)],
                ["", ""],
            ],
        ], colWidths=["50%", "50%"], style=TableStyle([
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ("LEFTPADDING", (0, 0), (-1, -1), 0),
            ("RIGHTPADDING", (0, 0), (-1, -1), 8),
        ]))
    ]

    # --- Applicant #1 Prior Employment ---
    if data.get("prior_employer_name"):
        story += section("APPLICANT #1 — PRIOR EMPLOYMENT")
        story += [
            Table([
                [
                    [Paragraph("Prior Employer", label_style), Paragraph(data.get("prior_employer_name") or "—", value_style)],
                    [Paragraph("Position Held", label_style), Paragraph(data.get("prior_position_held") or "—", value_style)],
                    [Paragraph("Length", label_style), Paragraph(data.get("prior_length_of_employment") or "—", value_style)],
                ],
            ], colWidths=["40%", "35%", "25%"], style=TableStyle([
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("LEFTPADDING", (0, 0), (-1, -1), 0),
                ("RIGHTPADDING", (0, 0), (-1, -1), 8),
            ]))
        ]

    # --- Co-applicants ---
    co_applicants = data.get("co_applicants") or []
    if co_applicants:
        for i, co in enumerate(co_applicants, start=2):
            story += section(f"APPLICANT #{i}")
            story += [
                Table([
                    [
                        [Paragraph("Full Name", label_style), Paragraph(co.get("name") or "—", value_style)],
                        [Paragraph("Occupation", label_style), Paragraph(co.get("occupation") or "—", value_style)],
                        [Paragraph("Monthly Income", label_style), Paragraph(f"${co.get('monthly_income') or '—'}", value_style)],
                    ],
                ], colWidths=["40%", "35%", "25%"], style=TableStyle([
                    ("VALIGN", (0, 0), (-1, -1), "TOP"),
                    ("LEFTPADDING", (0, 0), (-1, -1), 0),
                    ("RIGHTPADDING", (0, 0), (-1, -1), 8),
                ]))
            ]

    # --- Other Occupants ---
    other_occupants = data.get("other_occupants") or []
    if other_occupants:
        story += section("OTHER OCCUPANTS")
        rows = [[Paragraph("Name", label_style), Paragraph("Relationship", label_style), Paragraph("Age", label_style)]]
        for occ in other_occupants:
            rows.append([
                Paragraph(occ.get("name") or "—", value_style),
                Paragraph(occ.get("relationship") or "—", value_style),
                Paragraph(str(occ.get("age") or "—"), value_style),
            ])
        story.append(Table(rows, colWidths=["50%", "30%", "20%"], style=TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#f1f5f9")),
            ("FONTSIZE", (0, 0), (-1, -1), 9),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ("LEFTPADDING", (0, 0), (-1, -1), 4),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.lightgrey),
        ])))

    # --- Pets & Parking ---
    story += section("PETS & PARKING")
    story += [
        Table([
            [
                [Paragraph("Has Pet(s)", label_style), Paragraph("Yes" if data.get("has_pet") else "No", value_style)],
                [Paragraph("Pet Details", label_style), Paragraph(data.get("pet_details") or "—", value_style)],
            ],
            [
                [Paragraph("Parking Requested", label_style), Paragraph("Yes" if data.get("parking_requested") else "No", value_style)],
                ["", ""],
            ],
        ], colWidths=["30%", "70%"], style=TableStyle([
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ("LEFTPADDING", (0, 0), (-1, -1), 0),
            ("RIGHTPADDING", (0, 0), (-1, -1), 8),
        ]))
    ]

    # --- Previous Addresses ---
    prev_addresses = data.get("previous_addresses") or []
    if prev_addresses:
        story += section("PREVIOUS ADDRESSES")
        for addr in prev_addresses:
            story += [
                Table([
                    [
                        [Paragraph("Address", label_style), Paragraph(addr.get("address") or "—", value_style)],
                        [Paragraph("From", label_style), Paragraph(addr.get("from") or "—", value_style)],
                        [Paragraph("To", label_style), Paragraph(addr.get("to") or "—", value_style)],
                    ],
                    [
                        [Paragraph("Landlord Name", label_style), Paragraph(addr.get("landlord_name") or "—", value_style)],
                        [Paragraph("Landlord Phone", label_style), Paragraph(addr.get("landlord_phone") or "—", value_style)],
                        ["", ""],
                    ],
                ], colWidths=["50%", "25%", "25%"], style=TableStyle([
                    ("VALIGN", (0, 0), (-1, -1), "TOP"),
                    ("LEFTPADDING", (0, 0), (-1, -1), 0),
                    ("RIGHTPADDING", (0, 0), (-1, -1), 8),
                ]))
            ]

    # --- Vacating Reason ---
    if data.get("vacating_reason"):
        story += section("REASON FOR VACATING")
        story.append(Paragraph(data.get("vacating_reason"), value_style))

    # --- References ---
    story += section("PERSONAL REFERENCES")
    story += [
        Table([
            [
                [Paragraph("Reference 1 Name", label_style), Paragraph(data.get("reference_1_name") or "—", value_style)],
                [Paragraph("Reference 1 Phone", label_style), Paragraph(data.get("reference_1_phone") or "—", value_style)],
            ],
            [
                [Paragraph("Reference 2 Name", label_style), Paragraph(data.get("reference_2_name") or "—", value_style)],
                [Paragraph("Reference 2 Phone", label_style), Paragraph(data.get("reference_2_phone") or "—", value_style)],
            ],
        ], colWidths=["50%", "50%"], style=TableStyle([
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ("LEFTPADDING", (0, 0), (-1, -1), 0),
            ("RIGHTPADDING", (0, 0), (-1, -1), 8),
        ]))
    ]

    # --- Legal Notice ---
    story += section("APPLICANT DECLARATION")
    story.append(Paragraph(
        "The Applicant represents that all statements made above are true and correct. "
        "The Applicant is hereby notified that a consumer report containing credit and/or personal "
        "information may be referred to in connection with this rental. The Applicant authorizes the "
        "verification of the information contained in this application. "
        "This application is not a Rental or Lease Agreement.",
        small_style
    ))
    story.append(Spacer(1, 20))

    # --- Signature blocks (space reserved — stamper fills these in) ---
    story.append(Table([
        [
            [
                Paragraph("Signature of Applicant #1", label_style),
                Spacer(1, 50),  # space for signature image
                HRFlowable(width="90%", thickness=0.5, color=colors.gray),
                Paragraph("Date: _______________", small_style),
            ],
            [
                Paragraph("Signature of Applicant #2", label_style),
                Spacer(1, 50),  # space for signature image
                HRFlowable(width="90%", thickness=0.5, color=colors.gray),
                Paragraph("Date: _______________", small_style),
            ],
        ]
    ], colWidths=["50%", "50%"], style=TableStyle([
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("LEFTPADDING", (0, 0), (-1, -1), 0),
        ("RIGHTPADDING", (0, 0), (-1, -1), 8),
    ])))

    doc.build(story)
    pdf_bytes = buffer.getvalue()
    buffer.close()

    logger.info(f"📄 Form 410 PDF generated ({len(pdf_bytes)} bytes)")
    return pdf_bytes